application/modules/ucp/views/ucp.tpl
Avatar: Fix the Avatar size in UCP it was 100x100 but the max is 120x120
=> Avatar: Fix the Avatar size in UCP

application/emulators/Trinity_rbac_wod_soap.php, application/emulators/trinity_rbac_bfa_soap.php, application/emulators/trinity_rbac_cata_soap.php, application/emulators/trinity_rbac_legion_soap.php, application/emulators/trinity_rbac_mop_soap.php, application/emulators/trinity_rbac_soap.php, application/modules/donate/css/donate.css, application/modules/gm/views/panel.tpl, application/modules/store/css/store.css
Fixed some errors in emulators for the GM module - With Legion and BFA the GM module wont error out now.
Fixed some errors in emulator itself - Bad expansion naming
Fixed some CSS errors for the modules. - Wrong button sizes, etc.
=> Fixed some small errors in CSS for modules and some errors in emulators in general.

application/modules/register/controllers/getCaptcha.php, application/modules/register/views/register.tpl
Fixes issue regarding the register captcha
=> Fixes issue regarding the register captcha

application/modules/admin/models/logging_model.php, application/modules/login/controllers/login.php
Fix reflective XSS.
Fix Admin panels SQL Injection
=> Security Improvements.

application/modules/login/controllers/login.php, application/modules/ucp/controllers/settings.php, application/modules/ucp/js/settings.js
Updated the code for the `submitInfo()` function in the **UCP** module.
=> Added protection when submitting new user settings.

application/modules/guild/controllers/guild.php, application/modules/guild/views/guild.tpl
Code can be ran by editing your guild motd
=> Fix stored XSS in armory.

Security Practices.md
This is required I think.. would help a lot of servers.
=> Create Security Practices.md

application/emulators/trinity_rbac_soap.php, application/modules/admin/views/aclmanager/index.tpl
Tested on latest trinitycore + ingame and indeed this will fix sintax error and ticket isssues : https://github.com/FusionGen/FusionGEN/issues/61 and https://github.com/FusionGen/FusionGEN/issues/52
=> Fix soap sending items on srp6

application/emulators/trinity_rbac_soap.php
=> Fix gm ticket answer from website via ingame mail on trinitycore

application/modules/character/controllers/character.php, application/modules/character/views/character.tpl
Add fixes:
- Fix the error when there is no Spirit stats in the DB
- Added a check if maxpower7 exist in the emulator. Some cores don't have a maxpower7 in their DB anymore
=> Merge commits from Master-SRP6 to Master

application/emulators/trinity_rbac_sl_soap.php, application/modules/admin/controllers/accounts.php, application/modules/admin/models/accounts_model.php
=> Clean fix GMlvl fix for AC/TC

.gitignore, application/config/version.php, application/language/english/recovery.php, application/libraries/administrator.php, application/modules/admin/controllers/admin.php, application/modules/admin/views/dashboard.tpl, application/modules/password_recovery/controllers/password_recovery.php, application/modules/password_recovery/models/password_recovery_model.php, application/modules/password_recovery/views/password_recovery.tpl
Tested and working
Further tests required
=> Feature: recover username

application/modules/character/views/character.tpl
=> Fix characters class color in armory

debug.php
Right now it shows the error message
=> Show connection error in debug.php

application/config/fusion.php.dist, application/libraries/fusioneditor.php, application/libraries/template.php, application/themes/admin/template.tpl, application/third_party/MX/Controller.php, application/views/header.tpl
Implement back cdn function since its already in the installer and acp settings.
I did tested it , and it works fine .
=> CDN actually is not deprecated

application/modules/news/controllers/news.php
Test:
www.example.org/news/view/?//tmz1bd-jmdgufzdnjafi2algeih4w2ie-h9appu7yjy.r87.me
=> Fix fatal error "too few arguments"

install/SQL/database.sql
https://github.com/FusionGen/FusionGEN/issues/141
=> Add required database for store_groups

application/modules/auth/controllers/Auth.php, application/modules/register/controllers/Register.php, application/modules/register/js/validate.js, application/modules/register/language/english/register.php
https://github.com/FusionGen/FusionGEN/issues/164
=> credentials length

application/css/default.css
I hope those are the last ones :)
=> remove again duplicate css

application/modules/character/css/character.css, application/modules/character/views/character.tpl
update stats colors with a lot better looking ones from [official armory](https://assets.worldofwarcraft.com/static/character-profile.155ee79dcf865c08c6ce.css)
=> Update stats colors

application/modules/admin/views/edit_realm.tpl
fixed a small appearance issue in admin/settings realms where the first Realm name input form haven't top spacing
=> fixed a small appearance issue in acp

application/language/english/sidebox_poll.php, application/language/spanish/sidebox_poll.php, application/modules/sidebox_poll/views/poll_view.tpl
correct no active poll message when there's not any pool created and remove unused language
=> correct no active poll message

application/modules/mod/controllers/Bans.php, application/modules/mod/js/mod.js
Check for some more empty input fields in Mod pannel (for now).
=> Check for some more empty input fields

application/modules/admin/controllers/Menu.php, application/modules/admin/js/menu.js, application/modules/admin/views/menu/menu.tpl
https://github.com/FusionGen/FusionGEN/issues/193
=> Properly show new added menu links confirmation

application/config/social_media.php, application/css/tooltip.css, application/emulators/azerothcore_soap.php, application/emulators/cmangos_soap.php, application/emulators/mangos_one_two_sph_soap.php, application/emulators/mangos_three_sph_soap.php, application/emulators/mangos_zero_sph_soap.php, application/emulators/mop_soap.php, application/emulators/trinity_legion_soap.php, application/libraries/Administrator.php, application/libraries/Logger.php, application/libraries/Tasks.php, application/libraries/User.php, application/models/Characters_model.php, application/models/Cms_model.php, application/models/External_account_model.php
- convert tab to spaces
- trim some whitespaces
- added new empty line at the end of required files
=> Clean whitespaces part1

application/themes/default/assets/css/global/general.css, application/themes/default/assets/css/parts/sidebox.css, application/themes/default/assets/css/parts/sidebox_menu.css
This will fix the problem with broken spacing on sidebox titles.
=> cosmetic sidebar font fix

application/themes/default/assets/css/parts/page.css, application/views/breadcumb.tpl
Fix for: https://github.com/FusionGen/FusionGEN/issues/236
=> fix small cosmetic breadcumb arrow issue

application/modules/character/controllers/Character.php, application/modules/character/views/character.tpl
this shoud finally fix hunter power bar
=> Character power bars update

install/SQL/database.sql
https://codeigniter.com/userguide3/installation/upgrade_312.html
https://codeigniter.com/userguide3/libraries/sessions.html
=> Update “ci_sessions” database table

index.php
use the DIRECTORY_SEPARATOR constant instead of a hard coded forward slash “/”
https://www.codeigniter.com/userguide3/installation/upgrade_306.html
=> Update directory separators

application/modules/ucp/controllers/Avatar.php, application/themes/default/assets/css/parts/page.css, application/views/tinymce.tpl
Added breadcrumb on avatar page too
Updated font size to fit in page better (also on responsive)
Everything was tested and shoud not be any problems.
=> Add breadcrumb on avatar page too

system/core/Input.php, system/core/Router.php, system/database/DB_query_builder.php, system/helpers/cookie_helper.php, system/libraries/Pagination.php, system/libraries/Xmlrpc.php, system/libraries/Xmlrpcs.php
Merge of following ci fixes:
https://github.com/bcit-ci/CodeIgniter/commit/c707e65028d1d010c432c8ce453ffb99d126e978
https://github.com/bcit-ci/CodeIgniter/commit/a6faab2ebf082eefff9c2422fce016e49da548bf
https://github.com/bcit-ci/CodeIgniter/commit/3e5d10956b0b34c248b388a98b9cf41739dc5c2c
https://github.com/bcit-ci/CodeIgniter/commit/ca00ea86443d2b1563b0e1b51ce8225bd315e69e
https://github.com/bcit-ci/CodeIgniter/commit/8d80bef64b79f6cddc1e631760d862c563b525bf
Everything was tested, no issues.
=> More ci fixes merge

application/modules/armory/controllers/Armory.php
Fix invalid json error on armory search when using special characters.
=> Fix armory search error on special characters

application/libraries/Administrator.php, application/modules/errors/views/error.tpl
This will fix 404 page not found error in log.
=> Update 404 page redirect to our custom one when unauthorized access acp

application/config/cdn.php, application/modules/admin/views/settings.tpl
now cdn links are loaded directly from github
=> cdn warkaround fix

install/do_general.php, install/do_owner.php
Fix: https://github.com/FusionGen/FusionGEN/issues/279
=> Possible vulnerability fix in installer

application/modules/admin/js/settings.js, application/modules/admin/views/settings.tpl
This shoud let window reload after adding new realm in acp.
=> Fix return after adding new realm in acp

application/config/emulator_names.php, application/emulators/trinity_rbac_df_soap.php, application/emulators/trinity_rbac_sl_soap.php, application/libraries/User.php, application/models/External_account_model.php, application/modules/auth/controllers/Auth.php, application/modules/register/controllers/Register.php
`battlenet_accounts` table renamed `sha_pass_hash` column to `salt`.
=> Fixed crash on account registration with latest TrinityCore master commit (Dragonflight).

system/helpers/captcha_helper.php
Merge https://github.com/bcit-ci/CodeIgniter/pull/6256
=> fix generating captcha in PHP 8.1

application/modules/armory/language/english/armory.php, application/modules/armory/language/french/armory.php, application/modules/armory/language/spanish/armory.php, application/modules/armory/models/Armory_model.php, application/modules/armory/views/search.tpl
Change Armory search order to characters > guilds > items.
Trimm some whitespaces.
=> Small armory update

application/config/config.php, application/themes/default/assets/css/parts/header.css
Workaround tested fix for not opening top sites until we properly fix it.
=> Vote sites workaround

application/modules/character/controllers/Character.php
Close https://github.com/FusionGen/FusionGEN/issues/269
=> Fix character icon loading issue when cache is enabled

application/modules/store/js/store.js
=> Fix store cart updatePrice method

application/config/config.php, application/modules/vote/controllers/Vote.php, application/modules/vote/js/vote.js, application/modules/vote/views/vote.tpl
removed old workaround and properly disable vote buttons even when not refreshing the page
=> Update vote to also include csrf token
